_prefs: 
  baselayer: null
  mapid: unepwcmc.d8952968
  saveCenter: false
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -74.0053
  - 40.7123
  - 14
description: A label-les map for pure natural demonstration
format: jpeg95
interactivity_layer: ''
layers: 
  - mapbox_satellite_open
  - mapbox_satellite_plus
  - mapbox_satellite_full
  - mapbox_satellite_watermask
  - landuse
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
maxzoom: 22
minzoom: 0
name: biome demo
source: "mapbox:///mapbox.satellite,mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - label.mss
  - road.mss
  - poi.mss
  - admin.mss
template: ''
